# stocks.py - Complete stock universe of 500+ Indian & US equities

INDIAN_STOCKS = [
    # NIFTY 50 & Major Indian Equities (104 stocks)
    {'symbol': 'RELIANCE.NS', 'name': 'Reliance Industries', 'sector': 'Energy', 'country': 'India'},
    {'symbol': 'TCS.NS', 'name': 'Tata Consultancy Services', 'sector': 'Technology', 'country': 'India'},
    {'symbol': 'HDFCBANK.NS', 'name': 'HDFC Bank', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'INFY.NS', 'name': 'Infosys', 'sector': 'Technology', 'country': 'India'},
    {'symbol': 'ICICIBANK.NS', 'name': 'ICICI Bank', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'HINDUNILVR.NS', 'name': 'Hindustan Unilever', 'sector': 'Consumer', 'country': 'India'},
    {'symbol': 'SBIN.NS', 'name': 'State Bank of India', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'BHARTIARTL.NS', 'name': 'Bharti Airtel', 'sector': 'Telecom', 'country': 'India'},
    {'symbol': 'ITC.NS', 'name': 'ITC Limited', 'sector': 'Consumer', 'country': 'India'},
    {'symbol': 'LT.NS', 'name': 'Larsen & Toubro', 'sector': 'Construction', 'country': 'India'},
    {'symbol': 'HCLTECH.NS', 'name': 'HCL Technologies', 'sector': 'Technology', 'country': 'India'},
    {'symbol': 'ASIANPAINT.NS', 'name': 'Asian Paints', 'sector': 'Consumer', 'country': 'India'},
    {'symbol': 'AXISBANK.NS', 'name': 'Axis Bank', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'BAJFINANCE.NS', 'name': 'Bajaj Finance', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'MARUTI.NS', 'name': 'Maruti Suzuki', 'sector': 'Automotive', 'country': 'India'},
    {'symbol': 'TITAN.NS', 'name': 'Titan Company', 'sector': 'Consumer', 'country': 'India'},
    {'symbol': 'WIPRO.NS', 'name': 'Wipro', 'sector': 'Technology', 'country': 'India'},
    {'symbol': 'SUNPHARMA.NS', 'name': 'Sun Pharma', 'sector': 'Healthcare', 'country': 'India'},
    {'symbol': 'ULTRACEMCO.NS', 'name': 'UltraTech Cement', 'sector': 'Construction', 'country': 'India'},
    {'symbol': 'NTPC.NS', 'name': 'NTPC Limited', 'sector': 'Energy', 'country': 'India'},
    {'symbol': 'TATAMOTORS.NS', 'name': 'Tata Motors', 'sector': 'Automotive', 'country': 'India'},
    {'symbol': 'TATASTEEL.NS', 'name': 'Tata Steel', 'sector': 'Basic Materials', 'country': 'India'},
    {'symbol': 'POWERGRID.NS', 'name': 'Power Grid Corp', 'sector': 'Utilities', 'country': 'India'},
    {'symbol': 'ONGC.NS', 'name': 'ONGC', 'sector': 'Energy', 'country': 'India'},
    {'symbol': 'M&M.NS', 'name': 'Mahindra & Mahindra', 'sector': 'Automotive', 'country': 'India'},
    {'symbol': 'JSWSTEEL.NS', 'name': 'JSW Steel', 'sector': 'Basic Materials', 'country': 'India'},
    {'symbol': 'ADANIENT.NS', 'name': 'Adani Enterprises', 'sector': 'Conglomerate', 'country': 'India'},
    {'symbol': 'ADANIPORTS.NS', 'name': 'Adani Ports', 'sector': 'Infrastructure', 'country': 'India'},
    {'symbol': 'COALINDIA.NS', 'name': 'Coal India', 'sector': 'Energy', 'country': 'India'},
    {'symbol': 'BPCL.NS', 'name': 'Bharat Petroleum', 'sector': 'Energy', 'country': 'India'},
    {'symbol': 'GRASIM.NS', 'name': 'Grasim Industries', 'sector': 'Basic Materials', 'country': 'India'},
    {'symbol': 'BRITANNIA.NS', 'name': 'Britannia Industries', 'sector': 'Consumer', 'country': 'India'},
    {'symbol': 'TECHM.NS', 'name': 'Tech Mahindra', 'sector': 'Technology', 'country': 'India'},
    {'symbol': 'HEROMOTOCO.NS', 'name': 'Hero MotoCorp', 'sector': 'Automotive', 'country': 'India'},
    {'symbol': 'EICHERMOT.NS', 'name': 'Eicher Motors', 'sector': 'Automotive', 'country': 'India'},
    {'symbol': 'DIVISLAB.NS', 'name': 'Divis Laboratories', 'sector': 'Healthcare', 'country': 'India'},
    {'symbol': 'DRREDDY.NS', 'name': 'Dr. Reddys Laboratories', 'sector': 'Healthcare', 'country': 'India'},
    {'symbol': 'CIPLA.NS', 'name': 'Cipla', 'sector': 'Healthcare', 'country': 'India'},
    {'symbol': 'APOLLOHOSP.NS', 'name': 'Apollo Hospitals', 'sector': 'Healthcare', 'country': 'India'},
    {'symbol': 'INDUSINDBK.NS', 'name': 'IndusInd Bank', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'KOTAKBANK.NS', 'name': 'Kotak Mahindra Bank', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'BAJAJ-AUTO.NS', 'name': 'Bajaj Auto', 'sector': 'Automotive', 'country': 'India'},
    {'symbol': 'HDFCLIFE.NS', 'name': 'HDFC Life Insurance', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'SBILIFE.NS', 'name': 'SBI Life Insurance', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'HINDALCO.NS', 'name': 'Hindalco Industries', 'sector': 'Basic Materials', 'country': 'India'},
    {'symbol': 'TATACONSUM.NS', 'name': 'Tata Consumer Products', 'sector': 'Consumer', 'country': 'India'},
    {'symbol': 'NESTLEIND.NS', 'name': 'Nestle India', 'sector': 'Consumer', 'country': 'India'},
    {'symbol': 'PIDILITIND.NS', 'name': 'Pidilite Industries', 'sector': 'Chemicals', 'country': 'India'},
    {'symbol': 'SIEMENS.NS', 'name': 'Siemens India', 'sector': 'Industrials', 'country': 'India'},
    {'symbol': 'BEL.NS', 'name': 'Bharat Electronics', 'sector': 'Defense', 'country': 'India'},
    {'symbol': 'HAL.NS', 'name': 'Hindustan Aeronautics', 'sector': 'Defense', 'country': 'India'},
    {'symbol': 'DLF.NS', 'name': 'DLF Limited', 'sector': 'Real Estate', 'country': 'India'},
    {'symbol': 'IOC.NS', 'name': 'Indian Oil Corp', 'sector': 'Energy', 'country': 'India'},
    {'symbol': 'GAIL.NS', 'name': 'GAIL India', 'sector': 'Utilities', 'country': 'India'},
    {'symbol': 'REC.NS', 'name': 'REC Limited', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'PFC.NS', 'name': 'Power Finance Corp', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'VBL.NS', 'name': 'Varun Beverages', 'sector': 'Consumer', 'country': 'India'},
    {'symbol': 'ZOMATO.NS', 'name': 'Zomato', 'sector': 'Technology', 'country': 'India'},
    {'symbol': 'JIOFIN.NS', 'name': 'Jio Financial Services', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'PAYTM.NS', 'name': 'One97 Communications (Paytm)', 'sector': 'Technology', 'country': 'India'},
    {'symbol': 'TRENT.NS', 'name': 'Trent Limited', 'sector': 'Retail', 'country': 'India'},
    {'symbol': 'INDIGO.NS', 'name': 'InterGlobe Aviation (IndiGo)', 'sector': 'Aviation', 'country': 'India'},
    {'symbol': 'POLYCAB.NS', 'name': 'Polycab India', 'sector': 'Industrials', 'country': 'India'},
    {'symbol': 'SRF.NS', 'name': 'SRF Limited', 'sector': 'Chemicals', 'country': 'India'},
    {'symbol': 'COLPAL.NS', 'name': 'Colgate-Palmolive India', 'sector': 'Consumer', 'country': 'India'},
    {'symbol': 'BERGEPAINT.NS', 'name': 'Berger Paints', 'sector': 'Consumer', 'country': 'India'},
    {'symbol': 'MARICO.NS', 'name': 'Marico', 'sector': 'Consumer', 'country': 'India'},
    {'symbol': 'DABUR.NS', 'name': 'Dabur India', 'sector': 'Consumer', 'country': 'India'},
    {'symbol': 'GODREJCP.NS', 'name': 'Godrej Consumer Products', 'sector': 'Consumer', 'country': 'India'},
    {'symbol': 'MUTHOOTFIN.NS', 'name': 'Muthoot Finance', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'CHOLAFIN.NS', 'name': 'Cholamandalam Investment', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'TATAELXSI.NS', 'name': 'Tata Elxsi', 'sector': 'Technology', 'country': 'India'},
    {'symbol': 'PERSISTENT.NS', 'name': 'Persistent Systems', 'sector': 'Technology', 'country': 'India'},
    {'symbol': 'COFORGE.NS', 'name': 'Coforge', 'sector': 'Technology', 'country': 'India'},
    {'symbol': 'MPHASIS.NS', 'name': 'Mphasis', 'sector': 'Technology', 'country': 'India'},
    {'symbol': 'LTTS.NS', 'name': 'L&T Technology Services', 'sector': 'Technology', 'country': 'India'},
    {'symbol': 'LTIM.NS', 'name': 'LTIMindtree', 'sector': 'Technology', 'country': 'India'},
    {'symbol': 'IRCTC.NS', 'name': 'IRCTC', 'sector': 'Services', 'country': 'India'},
    {'symbol': 'RVNL.NS', 'name': 'Rail Vikas Nigam', 'sector': 'Infrastructure', 'country': 'India'},
    {'symbol': 'IRFC.NS', 'name': 'Indian Railway Finance', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'BHEL.NS', 'name': 'Bharat Heavy Electricals', 'sector': 'Industrials', 'country': 'India'},
    {'symbol': 'NHPC.NS', 'name': 'NHPC Limited', 'sector': 'Utilities', 'country': 'India'},
    {'symbol': 'SJVN.NS', 'name': 'SJVN Limited', 'sector': 'Utilities', 'country': 'India'},
    {'symbol': 'SAIL.NS', 'name': 'Steel Authority of India', 'sector': 'Basic Materials', 'country': 'India'},
    {'symbol': 'NMDC.NS', 'name': 'NMDC Limited', 'sector': 'Basic Materials', 'country': 'India'},
    {'symbol': 'NATIONALUM.NS', 'name': 'National Aluminium', 'sector': 'Basic Materials', 'country': 'India'},
    {'symbol': 'BANDHANBNK.NS', 'name': 'Bandhan Bank', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'BANKBARODA.NS', 'name': 'Bank of Baroda', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'PNB.NS', 'name': 'Punjab National Bank', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'CANBK.NS', 'name': 'Canara Bank', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'UNIONBANK.NS', 'name': 'Union Bank of India', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'IDFCFIRSTB.NS', 'name': 'IDFC First Bank', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'FEDERALBNK.NS', 'name': 'Federal Bank', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'AUBANK.NS', 'name': 'AU Small Finance Bank', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'MOTHERSON.NS', 'name': 'Samvardhana Motherson', 'sector': 'Automotive', 'country': 'India'},
    {'symbol': 'BOSCHLTD.NS', 'name': 'Bosch Limited', 'sector': 'Automotive', 'country': 'India'},
    {'symbol': 'MRF.NS', 'name': 'MRF Limited', 'sector': 'Automotive', 'country': 'India'},
    {'symbol': 'BALKRISIND.NS', 'name': 'Balkrishna Industries', 'sector': 'Automotive', 'country': 'India'},
    {'symbol': 'TUBEINVEST.NS', 'name': 'Tube Investments', 'sector': 'Industrials', 'country': 'India'},
    {'symbol': 'SUZLON.NS', 'name': 'Suzlon Energy', 'sector': 'Energy', 'country': 'India'},

    # Additional 150+ Live Indian Equities (Nifty Next 50, Midcap & Defense/PSU/Chemicals)
    {'symbol': 'ADANIGREEN.NS', 'name': 'Adani Green Energy', 'sector': 'Energy', 'country': 'India'},
    {'symbol': 'ADANIPOWER.NS', 'name': 'Adani Power', 'sector': 'Energy', 'country': 'India'},
    {'symbol': 'ADANITRANS.NS', 'name': 'Adani Energy Solutions', 'sector': 'Utilities', 'country': 'India'},
    {'symbol': 'ADANITOTAL.NS', 'name': 'Adani Total Gas', 'sector': 'Utilities', 'country': 'India'},
    {'symbol': 'AWL.NS', 'name': 'Adani Wilmar', 'sector': 'Consumer', 'country': 'India'},
    {'symbol': 'AMBUJACEM.NS', 'name': 'Ambuja Cements', 'sector': 'Construction', 'country': 'India'},
    {'symbol': 'ACC.NS', 'name': 'ACC Limited', 'sector': 'Construction', 'country': 'India'},
    {'symbol': 'ABB.NS', 'name': 'ABB India', 'sector': 'Industrials', 'country': 'India'},
    {'symbol': 'AARTIIND.NS', 'name': 'Aarti Industries', 'sector': 'Chemicals', 'country': 'India'},
    {'symbol': 'ABFRL.NS', 'name': 'Aditya Birla Fashion & Retail', 'sector': 'Retail', 'country': 'India'},
    {'symbol': 'ABCAPITAL.NS', 'name': 'Aditya Birla Capital', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'ALKEM.NS', 'name': 'Alkem Laboratories', 'sector': 'Healthcare', 'country': 'India'},
    {'symbol': 'APLLTD.NS', 'name': 'Alembic Pharmaceuticals', 'sector': 'Healthcare', 'country': 'India'},
    {'symbol': 'ASHOKLEY.NS', 'name': 'Ashok Leyland', 'sector': 'Automotive', 'country': 'India'},
    {'symbol': 'ASTRAL.NS', 'name': 'Astral Limited', 'sector': 'Construction', 'country': 'India'},
    {'symbol': 'AUROPHARMA.NS', 'name': 'Aurobindo Pharma', 'sector': 'Healthcare', 'country': 'India'},
    {'symbol': 'BALRAMCHIN.NS', 'name': 'Balrampur Chini Mills', 'sector': 'Agriculture', 'country': 'India'},
    {'symbol': 'BATAINDIA.NS', 'name': 'Bata India', 'sector': 'Consumer', 'country': 'India'},
    {'symbol': 'BHARATFORG.NS', 'name': 'Bharat Forge', 'sector': 'Defense', 'country': 'India'},
    {'symbol': 'BIOCON.NS', 'name': 'Biocon', 'sector': 'Healthcare', 'country': 'India'},
    {'symbol': 'BSOFT.NS', 'name': 'Birlasoft', 'sector': 'Technology', 'country': 'India'},
    {'symbol': 'CANFINHOME.NS', 'name': 'Can Fin Homes', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'CHAMBLFERT.NS', 'name': 'Chambal Fertilisers', 'sector': 'Chemicals', 'country': 'India'},
    {'symbol': 'CONCOR.NS', 'name': 'Container Corp of India', 'sector': 'Logistics', 'country': 'India'},
    {'symbol': 'COROMANDEL.NS', 'name': 'Coromandel International', 'sector': 'Chemicals', 'country': 'India'},
    {'symbol': 'CROMPTON.NS', 'name': 'Crompton Greaves Consumer', 'sector': 'Consumer', 'country': 'India'},
    {'symbol': 'CUMMINSIND.NS', 'name': 'Cummins India', 'sector': 'Industrials', 'country': 'India'},
    {'symbol': 'CYIENT.NS', 'name': 'Cyient', 'sector': 'Technology', 'country': 'India'},
    {'symbol': 'DEEPAKNTR.NS', 'name': 'Deepak Nitrite', 'sector': 'Chemicals', 'country': 'India'},
    {'symbol': 'DELHIVERY.NS', 'name': 'Delhivery', 'sector': 'Logistics', 'country': 'India'},
    {'symbol': 'DIXON.NS', 'name': 'Dixon Technologies', 'sector': 'Technology', 'country': 'India'},
    {'symbol': 'ESCORTS.NS', 'name': 'Escorts Kubota', 'sector': 'Automotive', 'country': 'India'},
    {'symbol': 'EXIDEIND.NS', 'name': 'Exide Industries', 'sector': 'Automotive', 'country': 'India'},
    {'symbol': 'FACT.NS', 'name': 'Fertilisers & Chemicals Travancore', 'sector': 'Chemicals', 'country': 'India'},
    {'symbol': 'FORTIS.NS', 'name': 'Fortis Healthcare', 'sector': 'Healthcare', 'country': 'India'},
    {'symbol': 'GLENMARK.NS', 'name': 'Glenmark Pharmaceuticals', 'sector': 'Healthcare', 'country': 'India'},
    {'symbol': 'GMRINFRA.NS', 'name': 'GMR Airports Infrastructure', 'sector': 'Infrastructure', 'country': 'India'},
    {'symbol': 'GNFC.NS', 'name': 'Gujarat Narmada Valley Fertilizers', 'sector': 'Chemicals', 'country': 'India'},
    {'symbol': 'GODREJPROP.NS', 'name': 'Godrej Properties', 'sector': 'Real Estate', 'country': 'India'},
    {'symbol': 'GRANULES.NS', 'name': 'Granules India', 'sector': 'Healthcare', 'country': 'India'},
    {'symbol': 'GSPL.NS', 'name': 'Gujarat State Petronet', 'sector': 'Utilities', 'country': 'India'},
    {'symbol': 'GUJGASLTD.NS', 'name': 'Gujarat Gas', 'sector': 'Utilities', 'country': 'India'},
    {'symbol': 'HAVELLS.NS', 'name': 'Havells India', 'sector': 'Consumer', 'country': 'India'},
    {'symbol': 'HDFCAMC.NS', 'name': 'HDFC Asset Management', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'HINDCOPPER.NS', 'name': 'Hindustan Copper', 'sector': 'Basic Materials', 'country': 'India'},
    {'symbol': 'HINDPETRO.NS', 'name': 'Hindustan Petroleum', 'sector': 'Energy', 'country': 'India'},
    {'symbol': 'HINDZINC.NS', 'name': 'Hindustan Zinc', 'sector': 'Basic Materials', 'country': 'India'},
    {'symbol': 'HUDCO.NS', 'name': 'Housing & Urban Development Corp', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'IDFC.NS', 'name': 'IDFC Limited', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'IEX.NS', 'name': 'Indian Energy Exchange', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'IGL.NS', 'name': 'Indraprastha Gas', 'sector': 'Utilities', 'country': 'India'},
    {'symbol': 'INDUSTOWER.NS', 'name': 'Indus Towers', 'sector': 'Telecom', 'country': 'India'},
    {'symbol': 'INFIBEAM.NS', 'name': 'Infibeam Avenues', 'sector': 'Technology', 'country': 'India'},
    {'symbol': 'IPCALAB.NS', 'name': 'IPCA Laboratories', 'sector': 'Healthcare', 'country': 'India'},
    {'symbol': 'IRB.NS', 'name': 'IRB Infrastructure Developers', 'sector': 'Infrastructure', 'country': 'India'},
    {'symbol': 'IREDA.NS', 'name': 'Indian Renewable Energy Dev', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'JINDALSTEL.NS', 'name': 'Jindal Steel & Power', 'sector': 'Basic Materials', 'country': 'India'},
    {'symbol': 'JSL.NS', 'name': 'Jindal Stainless', 'sector': 'Basic Materials', 'country': 'India'},
    {'symbol': 'JSWENERGY.NS', 'name': 'JSW Energy', 'sector': 'Energy', 'country': 'India'},
    {'symbol': 'JUBLFOOD.NS', 'name': 'Jubilant FoodWorks', 'sector': 'Consumer', 'country': 'India'},
    {'symbol': 'KALYANKJIL.NS', 'name': 'Kalyan Jewellers', 'sector': 'Retail', 'country': 'India'},
    {'symbol': 'KEI.NS', 'name': 'KEI Industries', 'sector': 'Industrials', 'country': 'India'},
    {'symbol': 'KPITTECH.NS', 'name': 'KPIT Technologies', 'sector': 'Technology', 'country': 'India'},
    {'symbol': 'LAURUSLABS.NS', 'name': 'Laurus Labs', 'sector': 'Healthcare', 'country': 'India'},
    {'symbol': 'LICHSGFIN.NS', 'name': 'LIC Housing Finance', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'LICI.NS', 'name': 'Life Insurance Corp of India', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'LUPIN.NS', 'name': 'Lupin Limited', 'sector': 'Healthcare', 'country': 'India'},
    {'symbol': 'MANAPPURAM.NS', 'name': 'Manappuram Finance', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'MAXHEALTH.NS', 'name': 'Max Healthcare Institute', 'sector': 'Healthcare', 'country': 'India'},
    {'symbol': 'MAZDOCK.NS', 'name': 'Mazagon Dock Shipbuilders', 'sector': 'Defense', 'country': 'India'},
    {'symbol': 'METROPOLIS.NS', 'name': 'Metropolis Healthcare', 'sector': 'Healthcare', 'country': 'India'},
    {'symbol': 'MFSL.NS', 'name': 'Max Financial Services', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'MGL.NS', 'name': 'Mahanagar Gas', 'sector': 'Utilities', 'country': 'India'},
    {'symbol': 'MCX.NS', 'name': 'Multi Commodity Exchange of India', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'NATCOPHARM.NS', 'name': 'Natco Pharma', 'sector': 'Healthcare', 'country': 'India'},
    {'symbol': 'NAVINFLUOR.NS', 'name': 'Navin Fluorine International', 'sector': 'Chemicals', 'country': 'India'},
    {'symbol': 'NAUKRI.NS', 'name': 'Info Edge India (Naukri)', 'sector': 'Technology', 'country': 'India'},
    {'symbol': 'NYKAA.NS', 'name': 'FSN E-Commerce (Nykaa)', 'sector': 'Retail', 'country': 'India'},
    {'symbol': 'OBEROIRLTY.NS', 'name': 'Oberoi Realty', 'sector': 'Real Estate', 'country': 'India'},
    {'symbol': 'OFSS.NS', 'name': 'Oracle Financial Services', 'sector': 'Technology', 'country': 'India'},
    {'symbol': 'OIL.NS', 'name': 'Oil India Limited', 'sector': 'Energy', 'country': 'India'},
    {'symbol': 'PAGEIND.NS', 'name': 'Page Industries (Jockey)', 'sector': 'Consumer', 'country': 'India'},
    {'symbol': 'PATANJALI.NS', 'name': 'Patanjali Foods', 'sector': 'Consumer', 'country': 'India'},
    {'symbol': 'PETRONET.NS', 'name': 'Petronet LNG', 'sector': 'Energy', 'country': 'India'},
    {'symbol': 'PHOENIXLTD.NS', 'name': 'Phoenix Mills', 'sector': 'Real Estate', 'country': 'India'},
    {'symbol': 'PIIND.NS', 'name': 'PI Industries', 'sector': 'Chemicals', 'country': 'India'},
    {'symbol': 'PNBHOUSING.NS', 'name': 'PNB Housing Finance', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'POLICYBZR.NS', 'name': 'PB Fintech (Policybazaar)', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'POONAWALLA.NS', 'name': 'Poonawalla Fincorp', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'PRESTIGE.NS', 'name': 'Prestige Estates Projects', 'sector': 'Real Estate', 'country': 'India'},
    {'symbol': 'RAILTEL.NS', 'name': 'RailTel Corp of India', 'sector': 'Telecom', 'country': 'India'},
    {'symbol': 'RAMCOCEM.NS', 'name': 'Ramco Cements', 'sector': 'Construction', 'country': 'India'},
    {'symbol': 'RCF.NS', 'name': 'Rashtriya Chemicals & Fertilizers', 'sector': 'Chemicals', 'country': 'India'},
    {'symbol': 'REDINGTON.NS', 'name': 'Redington India', 'sector': 'Technology', 'country': 'India'},
    {'symbol': 'RHIM.NS', 'name': 'RHI Magnesita India', 'sector': 'Basic Materials', 'country': 'India'},
    {'symbol': 'RITES.NS', 'name': 'RITES Limited', 'sector': 'Infrastructure', 'country': 'India'},
    {'symbol': 'SCHAEFFLER.NS', 'name': 'Schaeffler India', 'sector': 'Industrials', 'country': 'India'},
    {'symbol': 'SHREECEM.NS', 'name': 'Shree Cement', 'sector': 'Construction', 'country': 'India'},
    {'symbol': 'SHRIRAMFIN.NS', 'name': 'Shriram Finance', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'SONACOMS.NS', 'name': 'Sona BLW Precision Forgings', 'sector': 'Automotive', 'country': 'India'},
    {'symbol': 'STARHEALTH.NS', 'name': 'Star Health Insurance', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'SUMICHEM.NS', 'name': 'Sumitomo Chemical India', 'sector': 'Chemicals', 'country': 'India'},
    {'symbol': 'SUNDARMFIN.NS', 'name': 'Sundaram Finance', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'SUNTV.NS', 'name': 'Sun TV Network', 'sector': 'Entertainment', 'country': 'India'},
    {'symbol': 'SUPREMEIND.NS', 'name': 'Supreme Industries', 'sector': 'Industrials', 'country': 'India'},
    {'symbol': 'SYNGENE.NS', 'name': 'Syngene International', 'sector': 'Healthcare', 'country': 'India'},
    {'symbol': 'TATACOMM.NS', 'name': 'Tata Communications', 'sector': 'Telecom', 'country': 'India'},
    {'symbol': 'TATAINVEST.NS', 'name': 'Tata Investment Corp', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'TATAPOWER.NS', 'name': 'Tata Power', 'sector': 'Energy', 'country': 'India'},
    {'symbol': 'TATATECH.NS', 'name': 'Tata Technologies', 'sector': 'Technology', 'country': 'India'},
    {'symbol': 'TEJASNET.NS', 'name': 'Tejas Networks', 'sector': 'Telecom', 'country': 'India'},
    {'symbol': 'THYROCARE.NS', 'name': 'Thyrocare Technologies', 'sector': 'Healthcare', 'country': 'India'},
    {'symbol': 'TORNTPOWER.NS', 'name': 'Torrent Power', 'sector': 'Utilities', 'country': 'India'},
    {'symbol': 'TORNTPHARM.NS', 'name': 'Torrent Pharmaceuticals', 'sector': 'Healthcare', 'country': 'India'},
    {'symbol': 'UBL.NS', 'name': 'United Breweries', 'sector': 'Consumer', 'country': 'India'},
    {'symbol': 'UCOBANK.NS', 'name': 'UCO Bank', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'UNOMINDA.NS', 'name': 'Uno Minda', 'sector': 'Automotive', 'country': 'India'},
    {'symbol': 'UPL.NS', 'name': 'UPL Limited', 'sector': 'Chemicals', 'country': 'India'},
    {'symbol': 'VOLTAS.NS', 'name': 'Voltas Limited', 'sector': 'Consumer', 'country': 'India'},
    {'symbol': 'WHIRLPOOL.NS', 'name': 'Whirlpool of India', 'sector': 'Consumer', 'country': 'India'},
    {'symbol': 'YESBANK.NS', 'name': 'Yes Bank', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'ZEEL.NS', 'name': 'Zee Entertainment', 'sector': 'Entertainment', 'country': 'India'},
    {'symbol': 'ZYDUSLIFE.NS', 'name': 'Zydus Lifesciences', 'sector': 'Healthcare', 'country': 'India'},
    {'symbol': 'COCHINSHIP.NS', 'name': 'Cochin Shipyard', 'sector': 'Defense', 'country': 'India'},
    {'symbol': 'SOLARINDS.NS', 'name': 'Solar Industries India', 'sector': 'Defense', 'country': 'India'},
    {'symbol': 'DATAPATTNS.NS', 'name': 'Data Patterns India', 'sector': 'Defense', 'country': 'India'},
    {'symbol': 'MAPMYINDIA.NS', 'name': 'CE Info Systems (MapmyIndia)', 'sector': 'Technology', 'country': 'India'},
    {'symbol': 'KFINTECH.NS', 'name': 'KFin Technologies', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'CAMS.NS', 'name': 'Computer Age Management Services', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'CDSL.NS', 'name': 'Central Depository Services', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'BSE.NS', 'name': 'BSE Limited', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'ANGELONE.NS', 'name': 'Angel One', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'IIFL.NS', 'name': 'IIFL Finance', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'MANKIND.NS', 'name': 'Mankind Pharma', 'sector': 'Healthcare', 'country': 'India'},
    {'symbol': 'DOMS.NS', 'name': 'DOMS Industries', 'sector': 'Consumer', 'country': 'India'},
    {'symbol': 'HONASA.NS', 'name': 'Honasa Consumer (Mamaearth)', 'sector': 'Consumer', 'country': 'India'},
    {'symbol': 'EASEMYTRIP.NS', 'name': 'Easy Trip Planners', 'sector': 'Technology', 'country': 'India'},
    {'symbol': 'SIGNATURE.NS', 'name': 'Signatureglobal India', 'sector': 'Real Estate', 'country': 'India'},
    {'symbol': 'JSWINFRA.NS', 'name': 'JSW Infrastructure', 'sector': 'Infrastructure', 'country': 'India'},
    {'symbol': 'MOTILALOFS.NS', 'name': 'Motilal Oswal Financial Services', 'sector': 'Financial', 'country': 'India'},
    {'symbol': 'CHALET.NS', 'name': 'Chalet Hotels', 'sector': 'Real Estate', 'country': 'India'},
    {'symbol': 'LEMONTREE.NS', 'name': 'Lemon Tree Hotels', 'sector': 'Consumer', 'country': 'India'},
    {'symbol': 'INDIAMART.NS', 'name': 'IndiaMART InterMESH', 'sector': 'Technology', 'country': 'India'},
    {'symbol': 'JUSTDIAL.NS', 'name': 'Just Dial', 'sector': 'Technology', 'country': 'India'},
    {'symbol': 'ROUTE.NS', 'name': 'Route Mobile', 'sector': 'Technology', 'country': 'India'},
    {'symbol': 'HAPPSTMNDS.NS', 'name': 'Happiest Minds Technologies', 'sector': 'Technology', 'country': 'India'},
    {'symbol': 'TATACHEM.NS', 'name': 'Tata Chemicals', 'sector': 'Chemicals', 'country': 'India'},
    {'symbol': 'TATACOFFEE.NS', 'name': 'Tata Coffee', 'sector': 'Consumer', 'country': 'India'},
    {'symbol': 'GODREJIND.NS', 'name': 'Godrej Industries', 'sector': 'Conglomerate', 'country': 'India'},
    {'symbol': 'SWIGGY.NS', 'name': 'Swiggy Limited', 'sector': 'Technology', 'country': 'India'},
    {'symbol': 'OLAELEC.NS', 'name': 'Ola Electric Mobility', 'sector': 'Automotive', 'country': 'India'}
]

US_STOCKS = [
    # Large Cap & Mid Cap US Equities + ETFs (105 stocks)
    {'symbol': 'AAPL', 'name': 'Apple Inc.', 'sector': 'Technology', 'country': 'US'},
    {'symbol': 'MSFT', 'name': 'Microsoft', 'sector': 'Technology', 'country': 'US'},
    {'symbol': 'GOOGL', 'name': 'Alphabet Inc.', 'sector': 'Technology', 'country': 'US'},
    {'symbol': 'AMZN', 'name': 'Amazon.com', 'sector': 'Retail', 'country': 'US'},
    {'symbol': 'NVDA', 'name': 'NVIDIA Corp', 'sector': 'Semiconductors', 'country': 'US'},
    {'symbol': 'META', 'name': 'Meta Platforms', 'sector': 'Technology', 'country': 'US'},
    {'symbol': 'TSLA', 'name': 'Tesla Inc.', 'sector': 'Automotive', 'country': 'US'},
    {'symbol': 'JPM', 'name': 'JPMorgan Chase', 'sector': 'Financial', 'country': 'US'},
    {'symbol': 'VTI', 'name': 'Vanguard Total Stock', 'sector': 'ETF', 'country': 'US'},
    {'symbol': 'VOO', 'name': 'Vanguard S&P 500', 'sector': 'ETF', 'country': 'US'},
    {'symbol': 'UNH', 'name': 'UnitedHealth Group', 'sector': 'Healthcare', 'country': 'US'},
    {'symbol': 'HD', 'name': 'Home Depot', 'sector': 'Retail', 'country': 'US'},
    {'symbol': 'PG', 'name': 'Procter & Gamble', 'sector': 'Consumer', 'country': 'US'},
    {'symbol': 'BAC', 'name': 'Bank of America', 'sector': 'Financial', 'country': 'US'},
    {'symbol': 'VZ', 'name': 'Verizon', 'sector': 'Telecom', 'country': 'US'},
    {'symbol': 'WMT', 'name': 'Walmart', 'sector': 'Retail', 'country': 'US'},
    {'symbol': 'NFLX', 'name': 'Netflix', 'sector': 'Entertainment', 'country': 'US'},
    {'symbol': 'DIS', 'name': 'Disney', 'sector': 'Entertainment', 'country': 'US'},
    {'symbol': 'PFE', 'name': 'Pfizer', 'sector': 'Healthcare', 'country': 'US'},
    {'symbol': 'KO', 'name': 'Coca-Cola', 'sector': 'Consumer', 'country': 'US'},
    {'symbol': 'AMD', 'name': 'Advanced Micro Devices', 'sector': 'Semiconductors', 'country': 'US'},
    {'symbol': 'INTC', 'name': 'Intel Corp.', 'sector': 'Semiconductors', 'country': 'US'},
    {'symbol': 'AVGO', 'name': 'Broadcom Inc.', 'sector': 'Semiconductors', 'country': 'US'},
    {'symbol': 'CRM', 'name': 'Salesforce Inc.', 'sector': 'Software', 'country': 'US'},
    {'symbol': 'ORCL', 'name': 'Oracle Corp.', 'sector': 'Software', 'country': 'US'},
    {'symbol': 'ADBE', 'name': 'Adobe Inc.', 'sector': 'Software', 'country': 'US'},
    {'symbol': 'CSCO', 'name': 'Cisco Systems', 'sector': 'Networking', 'country': 'US'},
    {'symbol': 'QCOM', 'name': 'Qualcomm Inc.', 'sector': 'Semiconductors', 'country': 'US'},
    {'symbol': 'IBM', 'name': 'IBM Corp.', 'sector': 'IT & Services', 'country': 'US'},
    {'symbol': 'WFC', 'name': 'Wells Fargo', 'sector': 'Financial', 'country': 'US'},
    {'symbol': 'GS', 'name': 'Goldman Sachs', 'sector': 'Financial', 'country': 'US'},
    {'symbol': 'MS', 'name': 'Morgan Stanley', 'sector': 'Financial', 'country': 'US'},
    {'symbol': 'V', 'name': 'Visa Inc.', 'sector': 'Payments', 'country': 'US'},
    {'symbol': 'MA', 'name': 'Mastercard Inc.', 'sector': 'Payments', 'country': 'US'},
    {'symbol': 'PYPL', 'name': 'PayPal Holdings', 'sector': 'Fintech', 'country': 'US'},
    {'symbol': 'SQ', 'name': 'Block Inc.', 'sector': 'Fintech', 'country': 'US'},
    {'symbol': 'COST', 'name': 'Costco Wholesale', 'sector': 'Retail', 'country': 'US'},
    {'symbol': 'NKE', 'name': 'NIKE Inc.', 'sector': 'Consumer', 'country': 'US'},
    {'symbol': 'SBUX', 'name': 'Starbucks Corp.', 'sector': 'Consumer', 'country': 'US'},
    {'symbol': 'PEP', 'name': 'PepsiCo Inc.', 'sector': 'Consumer', 'country': 'US'},
    {'symbol': 'XOM', 'name': 'Exxon Mobil', 'sector': 'Energy', 'country': 'US'},
    {'symbol': 'CVX', 'name': 'Chevron Corp.', 'sector': 'Energy', 'country': 'US'},
    {'symbol': 'QQQ', 'name': 'Invesco QQQ Trust', 'sector': 'ETF', 'country': 'US'},
    {'symbol': 'SPY', 'name': 'SPDR S&P 500 ETF', 'sector': 'ETF', 'country': 'US'},
    {'symbol': 'IWM', 'name': 'iShares Russell 2000', 'sector': 'ETF', 'country': 'US'},
    {'symbol': 'ABBV', 'name': 'AbbVie Inc.', 'sector': 'Healthcare', 'country': 'US'},
    {'symbol': 'JNJ', 'name': 'Johnson & Johnson', 'sector': 'Healthcare', 'country': 'US'},
    {'symbol': 'MRK', 'name': 'Merck & Co.', 'sector': 'Healthcare', 'country': 'US'},
    {'symbol': 'LLY', 'name': 'Eli Lilly and Co.', 'sector': 'Healthcare', 'country': 'US'},
    {'symbol': 'TMO', 'name': 'Thermo Fisher Scientific', 'sector': 'Healthcare', 'country': 'US'},
    {'symbol': 'ABT', 'name': 'Abbott Laboratories', 'sector': 'Healthcare', 'country': 'US'},
    {'symbol': 'DHR', 'name': 'Danaher Corp.', 'sector': 'Healthcare', 'country': 'US'},
    {'symbol': 'BMY', 'name': 'Bristol Myers Squibb', 'sector': 'Healthcare', 'country': 'US'},
    {'symbol': 'AMGN', 'name': 'Amgen Inc.', 'sector': 'Healthcare', 'country': 'US'},
    {'symbol': 'MDT', 'name': 'Medtronic plc', 'sector': 'Healthcare', 'country': 'US'},
    {'symbol': 'ISRG', 'name': 'Intuitive Surgical', 'sector': 'Healthcare', 'country': 'US'},
    {'symbol': 'BA', 'name': 'Boeing Co.', 'sector': 'Aerospace', 'country': 'US'},
    {'symbol': 'CAT', 'name': 'Caterpillar Inc.', 'sector': 'Industrials', 'country': 'US'},
    {'symbol': 'GE', 'name': 'General Electric', 'sector': 'Industrials', 'country': 'US'},
    {'symbol': 'HON', 'name': 'Honeywell International', 'sector': 'Industrials', 'country': 'US'},
    {'symbol': 'LMT', 'name': 'Lockheed Martin', 'sector': 'Defense', 'country': 'US'},
    {'symbol': 'RTX', 'name': 'RTX Corporation', 'sector': 'Defense', 'country': 'US'},
    {'symbol': 'UPS', 'name': 'United Parcel Service', 'sector': 'Logistics', 'country': 'US'},
    {'symbol': 'FDX', 'name': 'FedEx Corp.', 'sector': 'Logistics', 'country': 'US'},
    {'symbol': 'DE', 'name': 'Deere & Company', 'sector': 'Industrials', 'country': 'US'},
    {'symbol': 'MMM', 'name': '3M Company', 'sector': 'Industrials', 'country': 'US'},
    {'symbol': 'UNP', 'name': 'Union Pacific Corp.', 'sector': 'Transportation', 'country': 'US'},
    {'symbol': 'PLTR', 'name': 'Palantir Technologies', 'sector': 'Technology', 'country': 'US'},
    {'symbol': 'SNOW', 'name': 'Snowflake Inc.', 'sector': 'Technology', 'country': 'US'},
    {'symbol': 'UBER', 'name': 'Uber Technologies', 'sector': 'Technology', 'country': 'US'},
    {'symbol': 'ABNB', 'name': 'Airbnb Inc.', 'sector': 'Consumer', 'country': 'US'},
    {'symbol': 'COIN', 'name': 'Coinbase Global', 'sector': 'Fintech', 'country': 'US'},
    {'symbol': 'HOOD', 'name': 'Robinhood Markets', 'sector': 'Fintech', 'country': 'US'},
    {'symbol': 'PANW', 'name': 'Palo Alto Networks', 'sector': 'Cybersecurity', 'country': 'US'},
    {'symbol': 'CRWD', 'name': 'CrowdStrike Holdings', 'sector': 'Cybersecurity', 'country': 'US'},
    {'symbol': 'NET', 'name': 'Cloudflare Inc.', 'sector': 'Technology', 'country': 'US'},
    {'symbol': 'ZM', 'name': 'Zoom Video Communications', 'sector': 'Technology', 'country': 'US'},
    {'symbol': 'SHOP', 'name': 'Shopify Inc.', 'sector': 'E-Commerce', 'country': 'US'},
    {'symbol': 'SE', 'name': 'Sea Limited', 'sector': 'E-Commerce', 'country': 'US'},
    {'symbol': 'MELI', 'name': 'MercadoLibre Inc.', 'sector': 'E-Commerce', 'country': 'US'},
    {'symbol': 'SPOT', 'name': 'Spotify Technology', 'sector': 'Entertainment', 'country': 'US'},
    {'symbol': 'RBLX', 'name': 'Roblox Corp.', 'sector': 'Entertainment', 'country': 'US'},
    {'symbol': 'U', 'name': 'Unity Software', 'sector': 'Technology', 'country': 'US'},
    {'symbol': 'DOCU', 'name': 'DocuSign Inc.', 'sector': 'Software', 'country': 'US'},
    {'symbol': 'OKTA', 'name': 'Okta Inc.', 'sector': 'Cybersecurity', 'country': 'US'},
    {'symbol': 'TWLO', 'name': 'Twilio Inc.', 'sector': 'Software', 'country': 'US'},
    {'symbol': 'DDOG', 'name': 'Datadog Inc.', 'sector': 'Software', 'country': 'US'},
    {'symbol': 'ZS', 'name': 'Zscaler Inc.', 'sector': 'Cybersecurity', 'country': 'US'},
    {'symbol': 'MDB', 'name': 'MongoDB Inc.', 'sector': 'Software', 'country': 'US'},
    {'symbol': 'ESTC', 'name': 'Elastic N.V.', 'sector': 'Software', 'country': 'US'},
    {'symbol': 'PATH', 'name': 'UiPath Inc.', 'sector': 'Software', 'country': 'US'},
    {'symbol': 'AI', 'name': 'C3.ai Inc.', 'sector': 'Technology', 'country': 'US'},
    {'symbol': 'SMCI', 'name': 'Super Micro Computer', 'sector': 'Technology', 'country': 'US'},
    {'symbol': 'ARM', 'name': 'Arm Holdings', 'sector': 'Semiconductors', 'country': 'US'},
    {'symbol': 'TSM', 'name': 'Taiwan Semiconductor', 'sector': 'Semiconductors', 'country': 'US'},
    {'symbol': 'ASML', 'name': 'ASML Holding', 'sector': 'Semiconductors', 'country': 'US'},
    {'symbol': 'MU', 'name': 'Micron Technology', 'sector': 'Semiconductors', 'country': 'US'},
    {'symbol': 'AMAT', 'name': 'Applied Materials', 'sector': 'Semiconductors', 'country': 'US'},
    {'symbol': 'LRCX', 'name': 'Lam Research', 'sector': 'Semiconductors', 'country': 'US'},
    {'symbol': 'KLAC', 'name': 'KLA Corporation', 'sector': 'Semiconductors', 'country': 'US'},

    # Additional 150+ Live US Equities & ETFs (S&P 500, Cloud, AI, Fintech, Clean Energy & Healthcare)
    {'symbol': 'ANET', 'name': 'Arista Networks', 'sector': 'Networking', 'country': 'US'},
    {'symbol': 'NOW', 'name': 'ServiceNow Inc.', 'sector': 'Software', 'country': 'US'},
    {'symbol': 'WDAY', 'name': 'Workday Inc.', 'sector': 'Software', 'country': 'US'},
    {'symbol': 'TEAM', 'name': 'Atlassian Corp', 'sector': 'Software', 'country': 'US'},
    {'symbol': 'HUBS', 'name': 'HubSpot Inc.', 'sector': 'Software', 'country': 'US'},
    {'symbol': 'FTNT', 'name': 'Fortinet Inc.', 'sector': 'Cybersecurity', 'country': 'US'},
    {'symbol': 'GDDY', 'name': 'GoDaddy Inc.', 'sector': 'Technology', 'country': 'US'},
    {'symbol': 'TOST', 'name': 'Toast Inc.', 'sector': 'Fintech', 'country': 'US'},
    {'symbol': 'AFRM', 'name': 'Affirm Holdings', 'sector': 'Fintech', 'country': 'US'},
    {'symbol': 'UPST', 'name': 'Upstart Holdings', 'sector': 'Fintech', 'country': 'US'},
    {'symbol': 'SOFI', 'name': 'SoFi Technologies', 'sector': 'Fintech', 'country': 'US'},
    {'symbol': 'NU', 'name': 'Nu Holdings (Nubank)', 'sector': 'Fintech', 'country': 'US'},
    {'symbol': 'CPNG', 'name': 'Coupang Inc.', 'sector': 'E-Commerce', 'country': 'US'},
    {'symbol': 'GRAB', 'name': 'Grab Holdings', 'sector': 'Technology', 'country': 'US'},
    {'symbol': 'EBAY', 'name': 'eBay Inc.', 'sector': 'E-Commerce', 'country': 'US'},
    {'symbol': 'ETSY', 'name': 'Etsy Inc.', 'sector': 'E-Commerce', 'country': 'US'},
    {'symbol': 'CHWY', 'name': 'Chewy Inc.', 'sector': 'E-Commerce', 'country': 'US'},
    {'symbol': 'DKNG', 'name': 'DraftKings Inc.', 'sector': 'Entertainment', 'country': 'US'},
    {'symbol': 'PENN', 'name': 'PENN Entertainment', 'sector': 'Entertainment', 'country': 'US'},
    {'symbol': 'WYNN', 'name': 'Wynn Resorts', 'sector': 'Entertainment', 'country': 'US'},
    {'symbol': 'LVS', 'name': 'Las Vegas Sands', 'sector': 'Entertainment', 'country': 'US'},
    {'symbol': 'MAR', 'name': 'Marriott International', 'sector': 'Consumer', 'country': 'US'},
    {'symbol': 'HLT', 'name': 'Hilton Worldwide', 'sector': 'Consumer', 'country': 'US'},
    {'symbol': 'BKNG', 'name': 'Booking Holdings', 'sector': 'Consumer', 'country': 'US'},
    {'symbol': 'EXPE', 'name': 'Expedia Group', 'sector': 'Consumer', 'country': 'US'},
    {'symbol': 'LYFT', 'name': 'Lyft Inc.', 'sector': 'Technology', 'country': 'US'},
    {'symbol': 'DASH', 'name': 'DoorDash Inc.', 'sector': 'Technology', 'country': 'US'},
    {'symbol': 'TTD', 'name': 'The Trade Desk', 'sector': 'Technology', 'country': 'US'},
    {'symbol': 'ROKU', 'name': 'Roku Inc.', 'sector': 'Technology', 'country': 'US'},
    {'symbol': 'SNAP', 'name': 'Snap Inc.', 'sector': 'Technology', 'country': 'US'},
    {'symbol': 'PINS', 'name': 'Pinterest Inc.', 'sector': 'Technology', 'country': 'US'},
    {'symbol': 'IOT', 'name': 'Samsara Inc.', 'sector': 'Technology', 'country': 'US'},
    {'symbol': 'NTNX', 'name': 'Nutanix Inc.', 'sector': 'Software', 'country': 'US'},
    {'symbol': 'S', 'name': 'SentinelOne Inc.', 'sector': 'Cybersecurity', 'country': 'US'},
    {'symbol': 'NCNO', 'name': 'nCino Inc.', 'sector': 'Software', 'country': 'US'},
    {'symbol': 'GTLB', 'name': 'GitLab Inc.', 'sector': 'Software', 'country': 'US'},
    {'symbol': 'MNDY', 'name': 'monday.com', 'sector': 'Software', 'country': 'US'},
    {'symbol': 'BILL', 'name': 'BILL Holdings', 'sector': 'Fintech', 'country': 'US'},
    {'symbol': 'VEEV', 'name': 'Veeva Systems', 'sector': 'Healthcare', 'country': 'US'},
    {'symbol': 'SPLK', 'name': 'Splunk Inc.', 'sector': 'Software', 'country': 'US'},
    {'symbol': 'DELL', 'name': 'Dell Technologies', 'sector': 'Hardware', 'country': 'US'},
    {'symbol': 'HPQ', 'name': 'HP Inc.', 'sector': 'Hardware', 'country': 'US'},
    {'symbol': 'WDC', 'name': 'Western Digital', 'sector': 'Hardware', 'country': 'US'},
    {'symbol': 'STX', 'name': 'Seagate Technology', 'sector': 'Hardware', 'country': 'US'},
    {'symbol': 'NTAP', 'name': 'NetApp Inc.', 'sector': 'Hardware', 'country': 'US'},
    {'symbol': 'CELH', 'name': 'Celsius Holdings', 'sector': 'Consumer', 'country': 'US'},
    {'symbol': 'SYM', 'name': 'Symbotic Inc.', 'sector': 'Industrials', 'country': 'US'},
    {'symbol': 'APP', 'name': 'AppLovin Corp', 'sector': 'Technology', 'country': 'US'},
    {'symbol': 'PLUG', 'name': 'Plug Power Inc.', 'sector': 'Energy', 'country': 'US'},
    {'symbol': 'ENPH', 'name': 'Enphase Energy', 'sector': 'Energy', 'country': 'US'},
    {'symbol': 'SEDG', 'name': 'SolarEdge Technologies', 'sector': 'Energy', 'country': 'US'},
    {'symbol': 'FSLR', 'name': 'First Solar', 'sector': 'Energy', 'country': 'US'},
    {'symbol': 'RUN', 'name': 'Sunrun Inc.', 'sector': 'Energy', 'country': 'US'},
    {'symbol': 'LCID', 'name': 'Lucid Group', 'sector': 'Automotive', 'country': 'US'},
    {'symbol': 'RIVN', 'name': 'Rivian Automotive', 'sector': 'Automotive', 'country': 'US'},
    {'symbol': 'NIO', 'name': 'NIO Inc.', 'sector': 'Automotive', 'country': 'US'},
    {'symbol': 'XPEV', 'name': 'XPeng Inc.', 'sector': 'Automotive', 'country': 'US'},
    {'symbol': 'LI', 'name': 'Li Auto Inc.', 'sector': 'Automotive', 'country': 'US'},
    {'symbol': 'F', 'name': 'Ford Motor Company', 'sector': 'Automotive', 'country': 'US'},
    {'symbol': 'GM', 'name': 'General Motors', 'sector': 'Automotive', 'country': 'US'},
    {'symbol': 'TM', 'name': 'Toyota Motor Corp', 'sector': 'Automotive', 'country': 'US'},
    {'symbol': 'HMC', 'name': 'Honda Motor Co', 'sector': 'Automotive', 'country': 'US'},
    {'symbol': 'RACE', 'name': 'Ferrari N.V.', 'sector': 'Automotive', 'country': 'US'},
    {'symbol': 'SCHW', 'name': 'Charles Schwab Corp', 'sector': 'Financial', 'country': 'US'},
    {'symbol': 'BLK', 'name': 'BlackRock Inc.', 'sector': 'Financial', 'country': 'US'},
    {'symbol': 'BX', 'name': 'Blackstone Inc.', 'sector': 'Financial', 'country': 'US'},
    {'symbol': 'KKR', 'name': 'KKR & Co.', 'sector': 'Financial', 'country': 'US'},
    {'symbol': 'APO', 'name': 'Apollo Global Management', 'sector': 'Financial', 'country': 'US'},
    {'symbol': 'C', 'name': 'Citigroup Inc.', 'sector': 'Financial', 'country': 'US'},
    {'symbol': 'USB', 'name': 'U.S. Bancorp', 'sector': 'Financial', 'country': 'US'},
    {'symbol': 'PNC', 'name': 'PNC Financial Services', 'sector': 'Financial', 'country': 'US'},
    {'symbol': 'TFC', 'name': 'Truist Financial', 'sector': 'Financial', 'country': 'US'},
    {'symbol': 'COF', 'name': 'Capital One Financial', 'sector': 'Financial', 'country': 'US'},
    {'symbol': 'AXP', 'name': 'American Express', 'sector': 'Financial', 'country': 'US'},
    {'symbol': 'DFS', 'name': 'Discover Financial Services', 'sector': 'Financial', 'country': 'US'},
    {'symbol': 'SYF', 'name': 'Synchrony Financial', 'sector': 'Financial', 'country': 'US'},
    {'symbol': 'ALLY', 'name': 'Ally Financial', 'sector': 'Financial', 'country': 'US'},
    {'symbol': 'SO', 'name': 'Southern Company', 'sector': 'Utilities', 'country': 'US'},
    {'symbol': 'NEE', 'name': 'NextEra Energy', 'sector': 'Utilities', 'country': 'US'},
    {'symbol': 'DUK', 'name': 'Duke Energy', 'sector': 'Utilities', 'country': 'US'},
    {'symbol': 'D', 'name': 'Dominion Energy', 'sector': 'Utilities', 'country': 'US'},
    {'symbol': 'AEP', 'name': 'American Electric Power', 'sector': 'Utilities', 'country': 'US'},
    {'symbol': 'PCG', 'name': 'PG&E Corporation', 'sector': 'Utilities', 'country': 'US'},
    {'symbol': 'SRE', 'name': 'Sempra Energy', 'sector': 'Utilities', 'country': 'US'},
    {'symbol': 'XEL', 'name': 'Xcel Energy', 'sector': 'Utilities', 'country': 'US'},
    {'symbol': 'ED', 'name': 'Consolidated Edison', 'sector': 'Utilities', 'country': 'US'},
    {'symbol': 'COP', 'name': 'ConocoPhillips', 'sector': 'Energy', 'country': 'US'},
    {'symbol': 'EOG', 'name': 'EOG Resources', 'sector': 'Energy', 'country': 'US'},
    {'symbol': 'SLB', 'name': 'Schlumberger NV', 'sector': 'Energy', 'country': 'US'},
    {'symbol': 'HALLIBURTON', 'name': 'Halliburton Co.', 'sector': 'Energy', 'country': 'US'},
    {'symbol': 'BKR', 'name': 'Baker Hughes', 'sector': 'Energy', 'country': 'US'},
    {'symbol': 'MPC', 'name': 'Marathon Petroleum', 'sector': 'Energy', 'country': 'US'},
    {'symbol': 'PSX', 'name': 'Phillips 66', 'sector': 'Energy', 'country': 'US'},
    {'symbol': 'VLO', 'name': 'Valero Energy', 'sector': 'Energy', 'country': 'US'},
    {'symbol': 'OXY', 'name': 'Occidental Petroleum', 'sector': 'Energy', 'country': 'US'},
    {'symbol': 'PXD', 'name': 'Pioneer Natural Resources', 'sector': 'Energy', 'country': 'US'},
    {'symbol': 'DVN', 'name': 'Devon Energy', 'sector': 'Energy', 'country': 'US'},
    {'symbol': 'HES', 'name': 'Hess Corporation', 'sector': 'Energy', 'country': 'US'},
    {'symbol': 'APA', 'name': 'APA Corporation', 'sector': 'Energy', 'country': 'US'},
    {'symbol': 'MRO', 'name': 'Marathon Oil', 'sector': 'Energy', 'country': 'US'},
    {'symbol': 'KR', 'name': 'The Kroger Co.', 'sector': 'Retail', 'country': 'US'},
    {'symbol': 'TGT', 'name': 'Target Corporation', 'sector': 'Retail', 'country': 'US'},
    {'symbol': 'DLTR', 'name': 'Dollar Tree', 'sector': 'Retail', 'country': 'US'},
    {'symbol': 'DG', 'name': 'Dollar General', 'sector': 'Retail', 'country': 'US'},
    {'symbol': 'ROST', 'name': 'Ross Stores', 'sector': 'Retail', 'country': 'US'},
    {'symbol': 'TJX', 'name': 'The TJX Companies', 'sector': 'Retail', 'country': 'US'},
    {'symbol': 'ORLY', 'name': 'O\'Reilly Automotive', 'sector': 'Retail', 'country': 'US'},
    {'symbol': 'AZO', 'name': 'AutoZone Inc.', 'sector': 'Retail', 'country': 'US'},
    {'symbol': 'AAP', 'name': 'Advance Auto Parts', 'sector': 'Retail', 'country': 'US'},
    {'symbol': 'BBY', 'name': 'Best Buy Co.', 'sector': 'Retail', 'country': 'US'},
    {'symbol': 'LULU', 'name': 'Lululemon Athletica', 'sector': 'Consumer', 'country': 'US'},
    {'symbol': 'DECK', 'name': 'Deckers Outdoor (HOKA)', 'sector': 'Consumer', 'country': 'US'},
    {'symbol': 'BIRK', 'name': 'Birkenstock Holding', 'sector': 'Consumer', 'country': 'US'},
    {'symbol': 'ONON', 'name': 'On Holding AG (On Running)', 'sector': 'Consumer', 'country': 'US'},
    {'symbol': 'ANF', 'name': 'Abercrombie & Fitch', 'sector': 'Consumer', 'country': 'US'},
    {'symbol': 'ULTA', 'name': 'Ulta Beauty', 'sector': 'Consumer', 'country': 'US'},
    {'symbol': 'EL', 'name': 'The Estée Lauder Companies', 'sector': 'Consumer', 'country': 'US'},
    {'symbol': 'CL', 'name': 'Colgate-Palmolive', 'sector': 'Consumer', 'country': 'US'},
    {'symbol': 'KMB', 'name': 'Kimberly-Clark', 'sector': 'Consumer', 'country': 'US'},
    {'symbol': 'GIS', 'name': 'General Mills', 'sector': 'Consumer', 'country': 'US'},
    {'symbol': 'K', 'name': 'Kellanova', 'sector': 'Consumer', 'country': 'US'},
    {'symbol': 'HSY', 'name': 'The Hershey Company', 'sector': 'Consumer', 'country': 'US'},
    {'symbol': 'MDLZ', 'name': 'Mondelēz International', 'sector': 'Consumer', 'country': 'US'},
    {'symbol': 'STZ', 'name': 'Constellation Brands', 'sector': 'Consumer', 'country': 'US'},
    {'symbol': 'TAP', 'name': 'Molson Coors Beverage', 'sector': 'Consumer', 'country': 'US'},
    {'symbol': 'BUD', 'name': 'Anheuser-Busch InBev', 'sector': 'Consumer', 'country': 'US'},
    {'symbol': 'DEO', 'name': 'Diageo plc', 'sector': 'Consumer', 'country': 'US'},
    {'symbol': 'MNST', 'name': 'Monster Beverage', 'sector': 'Consumer', 'country': 'US'},
    {'symbol': 'REGN', 'name': 'Regeneron Pharmaceuticals', 'sector': 'Healthcare', 'country': 'US'},
    {'symbol': 'VRTX', 'name': 'Vertex Pharmaceuticals', 'sector': 'Healthcare', 'country': 'US'},
    {'symbol': 'BIIB', 'name': 'Biogen Inc.', 'sector': 'Healthcare', 'country': 'US'},
    {'symbol': 'GILD', 'name': 'Gilead Sciences', 'sector': 'Healthcare', 'country': 'US'},
    {'symbol': 'ALNY', 'name': 'Alnylam Pharmaceuticals', 'sector': 'Healthcare', 'country': 'US'},
    {'symbol': 'INCY', 'name': 'Incyte Corporation', 'sector': 'Healthcare', 'country': 'US'},
    {'symbol': 'ILMN', 'name': 'Illumina Inc.', 'sector': 'Healthcare', 'country': 'US'},
    {'symbol': 'DXCM', 'name': 'DexCom Inc.', 'sector': 'Healthcare', 'country': 'US'},
    {'symbol': 'PODD', 'name': 'Insulet Corporation', 'sector': 'Healthcare', 'country': 'US'},
    {'symbol': 'EW', 'name': 'Edwards Lifesciences', 'sector': 'Healthcare', 'country': 'US'},
    {'symbol': 'SYK', 'name': 'Stryker Corporation', 'sector': 'Healthcare', 'country': 'US'},
    {'symbol': 'BSX', 'name': 'Boston Scientific', 'sector': 'Healthcare', 'country': 'US'},
    {'symbol': 'ZTS', 'name': 'Zoetis Inc.', 'sector': 'Healthcare', 'country': 'US'},
    {'symbol': 'IDXX', 'name': 'IDEXX Laboratories', 'sector': 'Healthcare', 'country': 'US'},
    {'symbol': 'IQV', 'name': 'IQVIA Holdings', 'sector': 'Healthcare', 'country': 'US'},
    {'symbol': 'A', 'name': 'Agilent Technologies', 'sector': 'Healthcare', 'country': 'US'},
    {'symbol': 'COR', 'name': 'Cencora Inc.', 'sector': 'Healthcare', 'country': 'US'},
    {'symbol': 'MCK', 'name': 'McKesson Corp', 'sector': 'Healthcare', 'country': 'US'},
    {'symbol': 'CAH', 'name': 'Cardinal Health', 'sector': 'Healthcare', 'country': 'US'},
    {'symbol': 'CI', 'name': 'Cigna Group', 'sector': 'Healthcare', 'country': 'US'},
    {'symbol': 'CVS', 'name': 'CVS Health Corp', 'sector': 'Healthcare', 'country': 'US'},
    {'symbol': 'HUM', 'name': 'Humana Inc.', 'sector': 'Healthcare', 'country': 'US'}
]

# Combine for 500+ stock universe
ALL_STOCKS = INDIAN_STOCKS + US_STOCKS
