"""Initial schema

Revision ID: a3dd931630f8
Revises: 
Create Date: 2026-09-05 00:17:25.501818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3dd931630f8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('news_sentiment', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('technical_position', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('market_beta', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('historical_volatility', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timestamp', name='uq_stock_snapshot_symbol_timestamp')
    )
    with op.batch_alter_table('stock_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_snapshots_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_snapshots_timestamp'), ['timestamp'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('user_stock_checkpoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('checkpoint_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('attention_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', 'checkpoint_time', name='uq_user_stock_checkpoint')
    )
    with op.batch_alter_table('user_stock_checkpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_stock_checkpoints_checkpoint_time'), ['checkpoint_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_stock_checkpoints_user_id'), ['user_id'], unique=False)

    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlists_user_id'), ['user_id'], unique=False)

    op.create_table('watchlist_stocks',
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('watchlist_id', 'symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_stocks')
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlists_user_id'))

    op.drop_table('watchlists')
    with op.batch_alter_table('user_stock_checkpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_stock_checkpoints_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_stock_checkpoints_checkpoint_time'))

    op.drop_table('user_stock_checkpoints')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('stock_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_snapshots_timestamp'))
        batch_op.drop_index(batch_op.f('ix_stock_snapshots_symbol'))

    op.drop_table('stock_snapshots')
    # ### end Alembic commands ###
